### ISSUE TITLE
Roadmap Version 1.0.0

### ISSUE THREAD

**Issue by AlexcastroDev** [AlexcastroDev/flexysearch#4]
Some functions to release the version 1.0.0

## String searcher:

- [x] Equals
- [x] #7
- [x] Contains
- [x] Does not contains
- [x] Starts with
- [x] Ends with
- [x] #9
- [x] #10

## Number searcher:

- [x] Equals
- [x] Different from
- [x] bigger than
- [x] smaller than
- [x] bigger or equals
- [x] smaller or equals
- [x] #11
- [x] #12

## Date Searcher

- [x] empty
- [x] is not empty
- [x] equals
- [x] Is not equals
- [x] after
- [x] before
- [x] Between
- [x] is on or after
- [x] is on or before

## Custom 
- [x] Allow Custom Filter
